// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRvCfajIZqAYfTVXZkgoFCssFj8AR-ihg',
    appId: '1:609749197084:web:36cd25d25abfdb1b6cdad9',
    messagingSenderId: '609749197084',
    projectId: 'flash-chat-4d92f',
    authDomain: 'flash-chat-4d92f.firebaseapp.com',
    storageBucket: 'flash-chat-4d92f.appspot.com',
    measurementId: 'G-D4TX06FFNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxsA8-jIoUNgFaMzWoycipFIhiLBeEOFI',
    appId: '1:609749197084:android:592ab579da4df7656cdad9',
    messagingSenderId: '609749197084',
    projectId: 'flash-chat-4d92f',
    storageBucket: 'flash-chat-4d92f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFXmeNEtysdRuienFODQDoHyS31iWbx2Y',
    appId: '1:609749197084:ios:12514972777749456cdad9',
    messagingSenderId: '609749197084',
    projectId: 'flash-chat-4d92f',
    storageBucket: 'flash-chat-4d92f.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFXmeNEtysdRuienFODQDoHyS31iWbx2Y',
    appId: '1:609749197084:ios:5d2e9b1618085efb6cdad9',
    messagingSenderId: '609749197084',
    projectId: 'flash-chat-4d92f',
    storageBucket: 'flash-chat-4d92f.appspot.com',
    iosBundleId: 'com.example.flashChat.RunnerTests',
  );
}
